sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
  - 2.4.4
  - 2.4.5
  - 2.4.6
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3
  - 2.5.4
  - 2.5.5
  - 2.6.0
  - 2.6.1
  - 2.6.2
  - 2.6.3
before_install: gem install bundler
